<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Message</name>
   <tag></tag>
   <elementGuidId>cd1bb1cb-fdfe-4ffa-92d0-ac61316bf93a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>997af77b-02ff-4b91-8f37-de444df2b982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swal2-title</value>
      <webElementGuid>db9800cf-d345-4712-abb2-21f47f0b1546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>swal2-title</value>
      <webElementGuid>121d3f9a-225d-4e8e-b8f1-95b59856f63c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thêm tài khoản thành công</value>
      <webElementGuid>37b47ae0-02eb-4f43-bfea-c8e081450b47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@class=&quot;swal2-container swal2-top-end swal2-backdrop-hide&quot;]/div[@class=&quot;swal2-popup swal2-modal swal2-icon-success swal2-hide&quot;]/h2[@id=&quot;swal2-title&quot;]</value>
      <webElementGuid>2a0617f0-7298-488e-90dc-f0b8c9c72ada</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'swal2-title' and (text() = 'Thêm tài khoản thành công' or . = 'Thêm tài khoản thành công')]</value>
      <webElementGuid>cd862411-a981-4ee3-9293-aada78426be1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
