<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>choice_msg</name>
   <tag></tag>
   <elementGuidId>f2f463b2-6d1d-4f16-a19e-661f45cbf8ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id=':r5m:-helper-text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Không được để trống bình chọn&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>5b19f5bf-ccd7-4335-bbf6-ea628bd02c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormHelperText-root Mui-error MuiFormHelperText-sizeMedium MuiFormHelperText-contained css-o1ds8i-MuiFormHelperText-root</value>
      <webElementGuid>2a1d1187-980a-4bb6-b7c0-67c5fa18e925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:r5m:-helper-text</value>
      <webElementGuid>2e193c5c-9573-465e-8538-0ea06cde3afb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Không được để trống bình chọn</value>
      <webElementGuid>9d3b76ab-c211-4dd6-b9e4-ce58d63e12be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r5m:-helper-text&quot;)</value>
      <webElementGuid>42df28b4-9095-44ca-856d-34c163055181</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id=':r5m:-helper-text']</value>
      <webElementGuid>90e94cf7-c00b-4862-bd0e-3cd6a737da8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lựa chọn 1 *'])[2]/following::p[1]</value>
      <webElementGuid>5e305082-883c-485f-bd43-6301134ec013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lựa chọn 1 *'])[1]/following::p[1]</value>
      <webElementGuid>320eb219-730f-4688-b453-621e03319afd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lựa chọn 2 *'])[1]/preceding::p[1]</value>
      <webElementGuid>1ce23176-b431-4486-a2a4-7ca5fda485a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lựa chọn 2 *'])[2]/preceding::p[1]</value>
      <webElementGuid>e93ee35f-b30e-4177-86e0-d61820bc8552</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Không được để trống bình chọn']/parent::*</value>
      <webElementGuid>5850bc58-92d6-4e73-9a7c-3eda24c2b36d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[3]/div/div/p</value>
      <webElementGuid>1646df4c-7ae3-47c7-bea6-68db5fb81444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = ':r5m:-helper-text' and (text() = 'Không được để trống bình chọn' or . = 'Không được để trống bình chọn')]</value>
      <webElementGuid>188e8639-83d0-400a-8cd4-bdbf1ec00cbf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
