<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>time_msg</name>
   <tag></tag>
   <elementGuidId>a34eb42e-a54b-4f99-8a0e-cb3fcdfb86fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id=':r5o:-helper-text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Thời hạn phải luôn lớn hơn thời điểm hiện tại&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>8c0dbe0c-75ec-4a09-bde7-e9b21055a760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormHelperText-root Mui-error MuiFormHelperText-sizeMedium MuiFormHelperText-contained MuiFormHelperText-filled css-o1ds8i-MuiFormHelperText-root</value>
      <webElementGuid>fb99cabd-645c-4617-aef6-406b77dc01fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:r5o:-helper-text</value>
      <webElementGuid>76e094e1-109f-49fd-ba5c-3b12e7eb1587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thời hạn phải luôn lớn hơn thời điểm hiện tại</value>
      <webElementGuid>25a80988-f0a1-4246-a895-c94ef767d49d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r5o:-helper-text&quot;)</value>
      <webElementGuid>c91aa1d9-30c4-4989-bcb9-21c175d166b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id=':r5o:-helper-text']</value>
      <webElementGuid>3935ee15-5ed8-4f11-aab7-39a4ece1a11e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thời hạn'])[2]/following::p[1]</value>
      <webElementGuid>c1bf2113-777f-4581-91d0-8f53df6a09f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thời hạn'])[1]/following::p[1]</value>
      <webElementGuid>8dab86d4-71cd-4d5e-ac67-2aa71be79167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hủy'])[1]/preceding::p[2]</value>
      <webElementGuid>a2fe7017-ec75-41f4-b45d-89a7ef52df63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tạo bình chọn'])[2]/preceding::p[2]</value>
      <webElementGuid>2511acc3-cccd-435d-bd66-8957bd695e90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thời hạn phải luôn lớn hơn thời điểm hiện tại']/parent::*</value>
      <webElementGuid>75fca14c-e67c-4206-89d9-f955ca9c0878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[4]/div/p</value>
      <webElementGuid>fba9beb7-0efb-478c-8399-d5f1858c88ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = ':r5o:-helper-text' and (text() = 'Thời hạn phải luôn lớn hơn thời điểm hiện tại' or . = 'Thời hạn phải luôn lớn hơn thời điểm hiện tại')]</value>
      <webElementGuid>70677049-dff3-45e2-ba66-f79a46053435</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
