<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_MentorUS_MuiAvatar-img css-1v6zmq-MuiAv_f9421d</name>
   <tag></tag>
   <elementGuidId>3c30818b-ce04-4340-8ff3-cc120e7919fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.MuiAvatar-img.css-1v6zmq-MuiAvatar-img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div[2]/button/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Admin&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b618e4e1-28f0-4888-9f2e-85efb5f37c79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>detail-image</value>
      <webElementGuid>39ca88ae-7d61-4318-8257-b812f5936679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://lh3.googleusercontent.com/a/ACg8ocIpH3jchDosg7Xy--GGd08kP5Ew0gs3eXuxfotBLpbJUkdK2g=s96-c</value>
      <webElementGuid>dbd40d90-8e61-4386-b208-6536aa00cc2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>referrerpolicy</name>
      <type>Main</type>
      <value>no-referrer</value>
      <webElementGuid>b9791fe2-74c3-493c-a139-aaad35334b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAvatar-img css-1v6zmq-MuiAvatar-img</value>
      <webElementGuid>25bb4629-c739-4cd3-bd49-680a3464d4ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;min-h-full w-full h-svh max-h-svh flex flex-row flex-grow overflow-hidden MuiBox-root css-0&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-wrap-xs-nowrap css-pad2pl-MuiGrid-root&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-auto !max-w-16 h-full css-1hx0a12-MuiGrid-root&quot;]/div[@class=&quot;flex flex-col justify-between h-full&quot;]/div[@class=&quot;h-16 flex flex-col hover:bg-sky-600&quot;]/button[@class=&quot;MuiButtonBase-root MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButton-colorPrimary MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButton-colorPrimary css-1vqs9o7-MuiButtonBase-root-MuiButton-root&quot;]/div[@class=&quot;MuiAvatar-root MuiAvatar-circular css-clv66y-MuiAvatar-root&quot;]/img[@class=&quot;MuiAvatar-img css-1v6zmq-MuiAvatar-img&quot;]</value>
      <webElementGuid>673be0ad-e53d-4f25-9b33-57a0b6ad0571</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/button/div/img</value>
      <webElementGuid>8da1d42c-1eec-45e1-81ee-6e55dde744ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='detail-image']</value>
      <webElementGuid>f5d3d90a-8c9e-4576-bea4-0eccbff7e579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>13faaf97-9efb-42ee-a1b0-2106dff40175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'detail-image' and @src = 'https://lh3.googleusercontent.com/a/ACg8ocIpH3jchDosg7Xy--GGd08kP5Ew0gs3eXuxfotBLpbJUkdK2g=s96-c']</value>
      <webElementGuid>d63859fe-2a86-4395-b86e-0ef30f7dcd54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
